
#Fichier de configuration des logs


#Propriétés globales:

# "handlers" : c'est une liste des gestionnaires de logs.
# Ils définissent où les messages seront envoyés (fichier, console...).
handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# Niveau de journalisation global par défaut.
.level= INFO

# Chemin et nom du fichier de log généré (ici dans le dossier config/)
java.util.logging.FileHandler.pattern = config/robotsim%u.log
# Taille maximale du fichier de log (en octets)
java.util.logging.FileHandler.limit = 5000000
# Nombre de fichiers de log à conserver (rotation)
java.util.logging.FileHandler.count = 1
# Nombre maximal de verrous pour l'accès concurrent au fichier de log
java.util.logging.FileHandler.maxLocks = 100
# Format utilisé pour écrire les logs dans le fichier (ici XML)
java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter

# Niveau minimal affiché dans la console (INFO et supérieur)
java.util.logging.ConsoleHandler.level = INFO
# Format d'affichage des logs dans la console (ici simple texte)
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

